In [52]:
import pandas as pd
df = pd.read_csv(f'../SensorLogFiles_my_iOS_device_230601_09-48-47/2023-05-31_20_23_09_Apple Watch.csv')
df = df.rename({'loggingTime(txt)':'t','accelerometerTimestamp_sinceReboot(s)':'t_acc','accelerometerAccelerationX(G)':'acc_x','accelerometerAccelerationY(G)':'acc_y','accelerometerAccelerationZ(G)':'acc_z','batteryLevel(R)':'battery'},axis=1)
df = df.drop('batteryState(N)',axis=1)
df['t'] = df['t'].astype('datetime64')

df

,t,t_acc,acc_x,acc_y,acc_z,battery
0,2023-06-01 00:23:09.551,5506.596322,-0.104950,-0.225388,-0.963867,0.87
1,2023-06-01 00:23:09.599,5506.646230,-0.094849,-0.243561,-0.959778,0.87
2,2023-06-01 00:23:09.649,5506.696137,-0.102509,-0.230347,-0.968674,0.87
3,2023-06-01 00:23:09.699,5506.746042,-0.088440,-0.252014,-0.971725,0.87
4,2023-06-01 00:23:09.749,5506.795949,-0.104904,-0.230453,-0.969666,0.87
...,...,...,...,...,...,...
130169,2023-06-01 02:28:06.550,12430.164782,0.182587,-0.085327,-0.987900,0.60
130170,2023-06-01 02:28:06.592,12430.214686,0.184662,-0.085541,-0.981812,0.60
130171,2023-06-01 02:28:06.651,12430.264590,0.184448,-0.082733,-0.982727,0.60
130172,2023-06-01 02:28:06.692,12430.314499,0.184372,-0.079437,-0.979309,0.60
130173,2023-06-01 02:28:06.742,12430.364403,0.185394,-0.081131,-0.973557,0.60

In [53]:
import plotly.express as px
fig = px.line(data_frame=df,y=['acc_x','acc_y','acc_z'])
fig.show(renderer='browser')